In [1]:
import pandas as pd

In [ ]:
df = pd.read_pickle('data/bank_data.pkl')

      day        type direction       amount      balance
0       0  CLIENT_OUT       out    643672.99  49356327.01
1       0  CLIENT_OUT       out   1313574.32  48042752.69
2       0  CLIENT_OUT       out    213857.87  47828894.82
3       0  LOAN_ISSUE       out  14819101.93  33009792.89
4       0   CLIENT_IN        in   1766171.22  34775964.11
...   ...         ...       ...          ...          ...
7167  364   CLIENT_IN        in   2154375.18  16736687.33
7168  364   CLIENT_IN        in   1333489.47  18070176.80
7169  364  CLIENT_OUT       out   4333449.79  13736727.01
7170  364  LOAN_ISSUE       out  15713855.42  10000000.00
7171  364   CLIENT_IN        in    255708.90  10255708.90

[7172 rows x 5 columns]

In [4]:
df_modified = df.groupby('day')['balance'].last().reset_index()
df_modified['lag_1'] = df_modified['balance'].shift(1)
df_modified['lag_7'] = df_modified['balance'].shift(7)
df_modified['lag_30'] = df_modified['balance'].shift(30)

In [5]:
df_modified['rolling_mean_7'] = df_modified['balance'].rolling(7).mean()
df_modified['rolling_std_7'] = df_modified['balance'].rolling(7).std()
df_modified['rolling_mean_30'] = df_modified['balance'].rolling(30).mean()
df_modified['rolling_std_30'] = df_modified['balance'].rolling(30).std()

In [6]:
df_modified['is_salary_day'] = df_modified['day'].apply(lambda x: 1 if x % 30 in [0, 15] else 0)
df_modified['is_tax_day'] = df_modified['day'].apply(lambda x: 1 if x % 30 == 28 else 0)

In [17]:
df_modified['target'] = df_modified['balance'].shift(-1)  # баланс следующего дня
df_modified = df_modified.dropna()
df

      day        type direction       amount      balance
0       0  CLIENT_OUT       out    643672.99  49356327.01
1       0  CLIENT_OUT       out   1313574.32  48042752.69
2       0  CLIENT_OUT       out    213857.87  47828894.82
3       0  LOAN_ISSUE       out  14819101.93  33009792.89
4       0   CLIENT_IN        in   1766171.22  34775964.11
...   ...         ...       ...          ...          ...
7167  364   CLIENT_IN        in   2154375.18  16736687.33
7168  364   CLIENT_IN        in   1333489.47  18070176.80
7169  364  CLIENT_OUT       out   4333449.79  13736727.01
7170  364  LOAN_ISSUE       out  15713855.42  10000000.00
7171  364   CLIENT_IN        in    255708.90  10255708.90

[7172 rows x 5 columns]

In [18]:
df_modified['total_in'] = df[df['direction'] == 'in'].groupby('day')['amount'].sum()
df_modified['total_out'] = df[df['direction'] == 'out'].groupby('day')['amount'].sum()

C:\Users\timur\AppData\Local\Temp\ipykernel_8344\2531798187.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified['total_in'] = df[df['direction'] == 'in'].groupby('day')['amount'].sum()
C:\Users\timur\AppData\Local\Temp\ipykernel_8344\2531798187.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified['total_out'] = df[df['direction'] == 'out'].groupby('day')['amount'].sum()

In [23]:
df_modified['n_transactions'] = df['day'].value_counts()

C:\Users\timur\AppData\Local\Temp\ipykernel_8344\2445196539.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified['n_transactions'] = df['day'].value_counts()

In [ ]:

df_modified.to_pickle('data/modified_bank_data.pickle')

In [25]:
df_modified

,day,balance,lag_1,lag_7,lag_30,rolling_mean_7,rolling_std_7,rolling_mean_30,rolling_std_30,is_salary_day,is_tax_day,target,total_in,total_out,n_transactions
30,30,22901231.36,24599274.85,37588469.10,31090044.22,2.282120e+07,8.599652e+06,2.085870e+07,8.996960e+06,1,0,42890311.69,41307554.30,43005597.81,24
31,31,42890311.69,22901231.36,22184064.32,10000000.00,2.577923e+07,1.143706e+07,2.195504e+07,9.611120e+06,0,0,48071923.34,37696906.51,17707826.20,21
32,32,48071923.34,42890311.69,39527824.63,16208117.91,2.699982e+07,1.343099e+07,2.301717e+07,1.065777e+07,0,0,38419238.51,36255077.78,31073466.14,22
33,33,38419238.51,48071923.34,13260981.74,15614638.43,3.059386e+07,1.247382e+07,2.377732e+07,1.092158e+07,0,0,29166903.04,36899038.26,46551723.09,22
34,34,29166903.04,38419238.51,14476104.39,16671272.90,3.269254e+07,1.036822e+07,2.419384e+07,1.087942e+07,0,0,15473510.17,25371934.53,34624269.99,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,358,48676576.54,45090837.69,25312555.14,57809802.55,5.239980e+07,1.527594e+07,3.380813e+07,2.116818e+07,0,1,31784426.89,41375884.51,37790145.66,23
359,359,31784426.89,48676576.54,26176229.14,25768550.50,5.320097e+07,1.374136e+07,3.400866e+07,2.111783e+07,0,0,12780275.01,23659262.27,40551411.90,24
360,360,12780275.01,31784426.89,55365676.07,10000000.00,4.711734e+07,2.042475e+07,3.410134e+07,2.101469e+07,1,0,13824334.95,38294113.11,57298264.99,24
361,361,13824334.95,12780275.01,75618827.73,14300101.00,3.828955e+07,1.938042e+07,3.408548e+07,2.103032e+07,0,0,11748166.83,34103890.14,55972123.75,20
362,362,11748166.83,13824334.95,53694631.79,10000000.00,3.229720e+07,2.028700e+07,3.414375e+07,2.096359e+07,0,0,16614402.99,24698638.90,53056761.56,22